name: 🚀 Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚀 Test
        shell: bash
        run: |
          python3 -m unittest tests/test_tree.py
